name: canada-ai-figures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pandas=2.3.3
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - numpy=2.2.6
  - statsmodels=0.14.6
  - plotnine=0.15.3
  - ipykernel=7.1.0
